sudo: true
language: java
jdk:
  #- openjdk7
  - oraclejdk7
before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
  - which thrift
install: /bin/true
script: mvn clean install -B
addons:
  # Fix OpenJDK 7 buffer overflows when the host name is too long.
  # https://docs.travis-ci.com/user/hostname
  hostname: travis-haeinsa
